### ISSUE TITLE
Wrong address on meet up

### ISSUE THREAD

**Issue by lupyana** [darjs/darjs.github.io#4]
The map on the dar js  [Meetup](https://www.meetup.com/dar-js/events/255177515/?action=rsvp&response=yes) page is wrong. it is written 

> Buni Innovation Hub,Ali Hassan Mwinyi Rd, Kijitonyama Dar es Salaam, Kinondoni · Dar es Salaam

but the map shows the old kinu address for some reason, im not sure if this is intended. I think it should be at Buni hub
![screenshot from 2018-10-03 01-22-26](https://user-images.githubusercontent.com/9304600/46380423-ded45f00-c6aa-11e8-88b3-d5086c7ec1af.png)

**Comment by mtuchi** [comment]
@joshuamabina :point_up:

**Comment by joshuamabina** [comment]
Thanks. It has been resolved.

**Comment by lupyana** [comment]
Awesome
